### ISSUE TITLE
Remove Swagger-ui from the repo.

### ISSUE THREAD

**Issue by jnallard** [Cimpress-MCP/Cimpress.Nancy#11]
The swagger-ui html, css, and js files are taking up most of the repository.  If the project using Cimpress.Nancy wants to include these files, that's their choice.

We should find a solution to remove these from this repo though.
One thing we could do is have a redirect from "/swagger/" to something like:
http://petstore.swagger.io/?url=http://localhost:port/api-docs
So that they can see their APIs while debugging. 

------------

OR if we want to have the swagger-ui pages directly served by Cimpress.Nancy, that would validate their existence, but we'd need to figure out how to do that.

**Comment by yahehe** [comment]
Agreed.

**Comment by jnallard** [comment]
Resolved by #19 
Closing

Look at the code percentages now! 
C# 97.6%
