### ISSUE TITLE
Refactor core concepts into individual projects

### ISSUE THREAD

**Issue by yahehe** [Cimpress-MCP/Cimpress.Nancy#12]
Create new packages for:
 - Logging
 - Authentication
 - Authorization
 - Swagger

This should allow users to pull down just what they need (e.g. if someone just wants to use just authentication or logging).

**Comment by jnallard** [comment]
Do you mind if I try tackling this? I think I have an architecture I want to test.

**Comment by yahehe** [comment]
Go for it

**Comment by yahehe** [comment]
#14
