### ISSUE TITLE
Update to VS 2017

### ISSUE THREAD

**Issue by jnallard** [Cimpress-MCP/Cimpress.Nancy#31]
We will probably need to do something similar to this PR that I did for Nancy.Swagger, since we basically used the same setup: https://github.com/yahehe/Nancy.Swagger/pull/97

**Comment by yahehe** [comment]
Done

**Comment by jnallard** [comment]
When did you update VS and the latest version of .Net Core?

**Comment by yahehe** [comment]
I updated VS last night

**Comment by jnallard** [comment]
That was a different project? 
There's no new commits on this one.

**Comment by yahehe** [comment]
Oh sorry, I didn't make any code changes I just updated the build image

**Comment by jnallard** [comment]
Alright, this should be good now.
