### ISSUE TITLE
Optional packages have a dependency on Cimpress.Nancy 1.0.26, not 1.0.26-alpha, causes compiler warning

### ISSUE THREAD

**Issue by jongoodnow** [Cimpress-MCP/Cimpress.Nancy#35]
Hello,

I'm getting the following compiler warnings on 1.0.26-alpha:

```
C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\NuGet.targets(97,5): warning : Detected package downgrade: Cimpress.Nancy from 1.0.26 to 1.0.26-alpha
C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\NuGet.targets(97,5): warning :  MyProject (>= 1.0.0) -> Cimpress.Nancy.Logging (>= 1.0.26-alpha) -> Cimpress.Nancy (>= 1.0.26)
C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\NuGet.targets(97,5): warning :  MyProject (>= 1.0.0) -> Cimpress.Nancy.Security (>= 1.0.26-alpha) -> Cimpress.Nancy (>= 1.0.26)
C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\NuGet.targets(97,5): warning :  MyProject (>= 1.0.0) -> Cimpress.Nancy.Swagger (>= 1.0.26-alpha) -> Cimpress.Nancy (>= 1.0.26)
```

Looking at the NuGet gallery pages, I can see Cimpress.Nancy.Logging, Security, and Swagger target Cimpress.Nancy 1.0.26 without the "-alpha." This doesn't affect the ability to use the library as far as I can tell, so it's a low priority issue, but I think it's worth fixing in your next version.

Thanks!

**Comment by jnallard** [comment]
I fixed this already for another project, so I can easily do it again. I'll put up a PR soon.
Thanks for bringing it to our attention!

**Comment by jongoodnow** [comment]
Awesome, thanks!

**Comment by yahehe** [comment]
New version is 1.0.27-alpha
