### ISSUE TITLE
Change Nuget Publish Key

### ISSUE THREAD

**Issue by yahehe** [Cimpress-MCP/Cimpress.Nancy#45]
The build pipeline is still publishing to Nuget with my API key. Might wanna change that :)

@jnallard

**Comment by jnallard** [comment]
Darn it! You leave the company and you're still telling me what to do!

(I'll fix it)

**Comment by jnallard** [comment]
Is `jnallard` an admin on the appveyor project? I didn't see it when I logged in.

(Did you add another email or something?)

Edit: I guess I should actually change Appveyor to my account anyways.

**Comment by yahehe** [comment]
Yeah either switch to your Appveyor or create one for the company (might wanna check with someone about the latter)

**Comment by yahehe** [comment]
@jnallard plsfixkthxbai

**Comment by jnallard** [comment]
@yahehe, disabled the hook to your Appveyor. I'll delete it once I have the new one running. 
I got mine set up and it's creating the nuget packages.
I think I need access to Cimpress.Nancy on Nuget so my apikey can actually push packages to it.
